const contactList = [
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:false
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Harshal",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"android",
        position:"Developer",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"Sonal",
        position:"android",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    {
        profileImage:"",
        name:"h",
        position:"android",
        email:"attardeharshal@gmail.com",
        phoneNumber:"888888888",
        Reveal:true
    },
    
]

export default contactList